<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
    <RootNamespace></RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants)TRACE;DEBUGTOOLS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants)TRACE;DEBUGTOOLS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineConstants>$(DefineConstants)TRACE;DEBUGTOOLS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DefineConstants>$(DefineConstants)TRACE;DEBUGTOOLS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="achievement\*" />
	<EmbeddedResource Include="armor\*" />
	<EmbeddedResource Include="art\*" />
	<EmbeddedResource Include="environment\*" />
	<EmbeddedResource Include="font\*" />
	<EmbeddedResource Include="gui\*" />
	<EmbeddedResource Include="item\*" />
	<EmbeddedResource Include="lang\*" />
	<EmbeddedResource Include="misc\*" />
	<EmbeddedResource Include="mob\*" />
	<EmbeddedResource Include="mob\*\*" />  
	<EmbeddedResource Include="terrain\*" />
	<EmbeddedResource Include="title\*" />
	<EmbeddedResource Include="title\*\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="argo\**" />
    <EmbeddedResource Remove="argo\**" />
    <None Remove="argo\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="font.txt" />
    <None Remove="pack.png" />
    <None Remove="pack.txt" />
    <None Remove="particles.png" />
    <None Remove="terrain.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="font.txt" />
    <EmbeddedResource Include="pack.png" />
    <EmbeddedResource Include="pack.txt" />
    <EmbeddedResource Include="particles.png" />
    <EmbeddedResource Include="terrain.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IKVM" Version="8.2.2-prerelease0553" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="OpenTK" Version="4.7.5" />
    <PackageReference Include="SharpZipLib" Version="1.4.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.3" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta15" />
    <PackageReference Include="TextCopy" Version="6.1.0" />
    <PackageReference Include="Varena" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BidiSharp">
      <HintPath>..\..\BidiSharp\BidiSharp\bin\Debug\netstandard2.0\BidiSharp.dll</HintPath>
    </Reference>
    <Reference Include="NVorbis">
      <HintPath>..\..\NVorbis\NVorbis\bin\Debug\netstandard2.0\NVorbis.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="shaders\fragment\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="shaders\vertex\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="net\minecraft\client\entity\ai\" />
  </ItemGroup>

</Project>
